---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-demo-stage
  namespace: news-demo-stage
  labels:
    app: news-demo-stage
spec:
  selector:
    matchLabels:
      app: news-demo-stage
  replicas: 1
  template:
    metadata:
      labels:
        app: news-demo-stage
    spec:
      containers:
        - name: news-demo-stage
          image: 996335758134.dkr.ecr.ap-northeast-1.amazonaws.com/tekton-and-argocd:23432
          ports:
            - containerPort: 3000
          env:
          - name: NEWS_API_KEY
            valueFrom:
              configMapKeyRef:
                name: news-demo-stage
                key: NEWS_API_KEY

