apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-demo-stage
  namespace: news-demo-stage
spec:
  rules:
    - host: news-demo-stage.apps.ci-ln-ycw3m0k-72292.origin-ci-int-gce.dev.rhcloud.com
      http:
        paths:
          - backend:
              service:
                name: news-demo-stage
                port:
                  number: 3000
            path: /
            pathType: Prefix
