apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-demo-dev
  namespace: news-demo-dev
spec:
  rules:
    - host: news-demo-dev.apps.shivam.devcluster.openshift.com
      http:
        paths:
          - backend:
              service:
                name: news-demo-dev
                port:
                  number: 3000
            path: /
            pathType: Prefix
